---
- hosts: all
  become: yes
  tasks:
    - name: test ping to hosts
      ping:
    
    - name: update apt and install git
      apt:
       name: git
       update_cache: yes
       state: present
       
    - name: install tree
      apt:
       name: tree
       state: present
     
       